#.travis.yml

language: node_js
node_js:
  - "8.9.1"

branches:
  only:
    - master
    - /^greenkeeper/.*$/

before_script:
  - npm install -g firebase-tools
  - npm install -g create-react-app

script:
  - npm run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change